{
  "comments": [
    {
      "key": {
        "uuid": "5adbc538_3c4ae883",
        "filename": "python-os-faults.spec",
        "patchSetId": 6
      },
      "lineNbr": 258,
      "author": {
        "id": 113
      },
      "writtenOn": "2016-11-10T14:26:54Z",
      "side": 1,
      "message": "Use * instead of %{version}. Otherwise, we can have issues.",
      "range": {
        "startLine": 258,
        "startChar": 31,
        "endLine": 258,
        "endChar": 43
      },
      "revId": "9900c2b70d59542e1f8fe032f174695a22791c2c",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5adbc538_5c4fb492",
        "filename": "python-os-faults.spec",
        "patchSetId": 6
      },
      "lineNbr": 277,
      "author": {
        "id": 113
      },
      "writtenOn": "2016-11-10T14:26:54Z",
      "side": 1,
      "message": "Use * instead of %{version}. Otherwise, we can have issues.",
      "range": {
        "startLine": 277,
        "startChar": 32,
        "endLine": 277,
        "endChar": 42
      },
      "revId": "9900c2b70d59542e1f8fe032f174695a22791c2c",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}